config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  get 'dip_tarija' => 'static_pages#dip_tarija'

  resources :contacts
  resources :work_posts

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :work_post
end

app/models/work_post.rb
class WorkPost < ActiveRecord::Base
	has_many :contacts, dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  skip_before_action :verify_authenticity_token, if: :json_request?

  protected
  
  def json_request?
    request.format.json?
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:info, :work_post_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  http_basic_authenticate_with name: "tarija", password: "tarija", only: :dip_tarija
  def index
  end

  def dip_tarija
  end
end

app/controllers/work_posts_controller.rb
class WorkPostsController < ApplicationController
  before_action :set_work_post, only: [:show, :edit, :update, :destroy]

  # GET /work_posts
  # GET /work_posts.json
  def index
    @work_posts = WorkPost.all
  end

  # GET /work_posts/1
  # GET /work_posts/1.json
  def show
  end

  # GET /work_posts/new
  def new
    @work_post = WorkPost.new
  end

  # GET /work_posts/1/edit
  def edit
  end

  # POST /work_posts
  # POST /work_posts.json
  def create
    @work_post = WorkPost.new(work_post_params.except(:contacts))

    respond_to do |format|
      if @work_post.save
        unless work_post_params[:contacts].nil?
          work_post_params[:contacts].each do |contact|
            Contact.create(info: contact, work_post: @work_post)
          end
        end
        format.html { redirect_to @work_post, notice: 'Work post was successfully created.' }
        format.json { render :show, status: :created, location: @work_post }
      else
        format.html { render :new }
        format.json { render json: @work_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_posts/1
  # PATCH/PUT /work_posts/1.json
  def update
    respond_to do |format|
      if @work_post.update(work_post_params)
        format.html { redirect_to @work_post, notice: 'Work post was successfully updated.' }
        format.json { render :show, status: :ok, location: @work_post }
      else
        format.html { render :edit }
        format.json { render json: @work_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_posts/1
  # DELETE /work_posts/1.json
  def destroy
    @work_post.destroy
    respond_to do |format|
      format.html { redirect_to work_posts_url, notice: 'Work post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_post
      @work_post = WorkPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_post_params
      params.require(:work_post).permit(:title, :description, contacts: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/work_posts_helper.rb
module WorkPostsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :info %><br>
    <%= f.text_field :info %>
  </div>
  <div class="field">
    <%= f.label :work_post_id %><br>
    <%= f.number_field :work_post_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Info</th>
      <th>Work post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.info %></td>
        <td><%= contact.work_post_id %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Info:</strong>
  <%= @contact.info %>
</p>

<p>
  <strong>Work post:</strong>
  <%= @contact.work_post_id %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Searchwork</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/dip_tarija.html.erb
<h1>Contenido</h1>

<ul>
	<li><%= link_to 'Hola Mundo', 'https://mega.nz/#!hkd0yYqL!nTHV1VkDKoj2cmv1HYMYKrZofLYX7gsfUCvd4f80a3I' %></li>
	<li><%= link_to 'Ejemplo Views', 'https://mega.nz/#!ppEQSJoL!CXGey5-mq7U9EBskEANT26wy7qBr2KDrtjiNoJw9n3Y' %></li>
	<li><%= link_to 'Ejemplo ListView', 'https://mega.nz/#!dhtHESoC!XLvKrQhUcaRFdBtizznDQqM8B8TTtlm81yxU2Z-vhpA' %></li>
	<li><%= link_to 'Presentaciones 1, 2 y 3', 'https://mega.nz/#!RgFSjTJK!LiJdO6jLi4oGjBOfSzZuBpLuAbKbWIdNBBHdWhfZ21Y' %></li>
	<li><%= link_to 'Ejercio ListView + Conexion a RED', 'https://mega.nz/#!o4NikZqL!kh4IsCeeF-3tCVGdy7qlJ10GXvq_rK9SLBRbB9PCPXY' %></li>
	<li><%= link_to 'Ejercio ListView + Conexion a RED + Custom Array Adapter', 'https://mega.nz/#!YhkBQTJD!Q1xsUCjwSttdwADUxwgWBP14WREeq8QCPFaRrix-Hqw' %></li>
	<li><%= link_to 'Ejercicio SQLite', 'https://mega.nz/#!9tVDBbwK!ZUF3nnUJz5dfRj8keSdQ_e9BGcVGX3w5nuATM536NHw' %></li>
	<li><%= link_to 'Ejercicio ContentProvider', 'https://mega.nz/#!d00jBbjJ!BIGuo97_7x1u4jf0iF3sDFA6Xj3UkABQLiTyeCYFl0k' %></li>
  <li><%= link_to 'Presentaciones 4 y 5', 'https://mega.nz/#!Fl1SjTQY!Rpo8KVDuJjy9ZeqREzCPo8PAPzeItqMwh0h5OS-HRAQ' %></li>
  <li><%= link_to 'Sunshine App (App de ejemplo)', 'https://github.com/udacity/Sunshine-Version-2' %></li>
  <li><%= link_to 'Enunciado Proyecto final', '/ProyectoFinalDipTarija.docx' %></li>
</ul>

app/views/static_pages/index.html.erb
<h1>Welcome</h1>
<p><%= link_to "Work Posts", work_posts_path(format: :json) %></p>
<p><%= link_to "Archivos dip Tarija 1 version", dip_tarija_path %></p>

<h2>Documentación de la API</h2>
<h3>Obtener todas los posts de trabajo</h3>
<code>
GET <%= work_posts_path %>.json
</code>

<h3>Insertar un post de trabajo</h3>
<code>
  POST <%= work_posts_path %>.json<br />
  Data:<br />
  {"work_post":{"title":"Title of the Job Post","description":"Text with the description","contacts":["Phone1", "Phone2", ..., "PhoneN"]}}
</code>

app/views/work_posts/_form.html.erb
<%= form_for(@work_post) do |f| %>
  <% if @work_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work_post.errors.count, "error") %> prohibited this work_post from being saved:</h2>

      <ul>
      <% @work_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/work_posts/edit.html.erb
<h1>Editing Work Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @work_post %> |
<%= link_to 'Back', work_posts_path %>

app/views/work_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Work Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @work_posts.each do |work_post| %>
      <tr>
        <td><%= work_post.title %></td>
        <td><%= work_post.description %></td>
        <td><%= link_to 'Show', work_post %></td>
        <td><%= link_to 'Edit', edit_work_post_path(work_post) %></td>
        <td><%= link_to 'Destroy', work_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work post', new_work_post_path %>

app/views/work_posts/new.html.erb
<h1>New Work Post</h1>

<%= render 'form' %>

<%= link_to 'Back', work_posts_path %>

app/views/work_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @work_post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @work_post.description %>
</p>

<%= link_to 'Edit', edit_work_post_path(@work_post) %> |
<%= link_to 'Back', work_posts_path %>